@EPayment.API_HostAddress = http://localhost:5000/api

GET {{ EPayment.API_HostAddress }}/weatherforecast/
Accept: application/json

###
GET {{ EPayment.API_HostAddress }}/Products/
Accept: application/json


###
GET {{ EPayment.API_HostAddress }}/Products/1
Accept: application/json

###
POST {{ EPayment.API_HostAddress }}/Products/CreateProduct/
Accept: application/json
Content-Type: application/json

{
  "name": "iPhone 15 Pro",
  "description": "Latest Apple phone",
  "price": 1299.99,
  "pictureUrl": "https://example.com/images/iphone15pro.png",
  "type": "Smartphone",
  "brand": "Apple",
  "quantity": 10
}
###